import user

print()
print("====")
print()
print("Formulario:")
print()
user.User["febre_temperatura"] = input("1. Qual a sua temperatura corporal?")
print()
user.User["febre_duracao"] = input("2. Qual a duracao da sua febre?")
print()
user.User["manchas_pele_dia"] = input("3. Em qual dia apareceram manchas na pele?")
print()
user.User["manchas_pele_frequencia"] = input("4. Qual a frequencia das suas manchas na pele?")
print()
user.User["dor_muscular"] = input("5. Qual a intensidade da sua dor muscular?")
print()
user.User["dor_articular_frequencia"] = input("6. Qual a frequencia da dor articular?")
print()
user.User["dor_articular_intensidade"] = input("7. Qual a intensidade da dor articular?")
print()
user.User["edema_articular_frequencia"] = input("8. Qual a frequencia do edema articular?")
print()
user.User["edema_articular_intensidade"] = input("9. Qual a intensidade do edema articular?")
print()
user.User["conjuntivite"] = input("10. Possui conjutivite?")
print()
user.User["enxaqueca"] = input("11. Qual a intensidade da enxaqueca?")
print()
user.User["coceira"] = input("12. Qual a intensidade da coceira?")
print()
user.User["hipertrofia_ganglionar"] = input("13. Houve hipertrofia ganglionar?")
print()
user.User["discrasia_hemorragica"] = input("14. Houve discrasia hemorragica?")
print()
user.User["acomentimento_neurologico"] = input("15. Houve acometimento neurológico?")

print(user.User)